name: flutter_tagging_demo
description: A Demo Application of Flutter Tagging.

version: 1.0.0+1

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  flutter_tagging:
    path: ../


dev_dependencies:
  flutter_test:
    sdk: flutter
  json_serializable: ^2.0.1
  build_runner: ^1.1.2


flutter:

  uses-material-design: true

